### ISSUE TITLE
How to extract ADF's origin(0,0,0) ?

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#68] opened 2016-12-20 10:44 UTC
How can I know the ADF's origin(0,0,0). I want to allign Unity's World origin with tango ADF's origin. 
The metadata doesnot contain anything.

**Comment by chaosemer** [comment] 2017-01-05 15:45
If you set the Delta Pose Controller or AR Pose Controller to Use the Area Description Pose, this will automatically happen. Note that since the Delta Pose Controller updates relative to where it starts, you'll want to make sure it is placed at 0,0,0 with no rotation.

Feel free to reply to this issue if you have other questions or close the issue if this works for you!

**Comment by chaosemer** [comment] 2017-01-11 20:15
Seems like the issue is solved. Please reopen if this is still an issue for you.

**Closed as completed by chaosemer** 2017-01-11 20:15 UTC

**Comment by imflash217** [comment] 2017-01-13 14:26
Sorry for late reply. This did resolved the issue. Thanks a lot buddy.
