### ISSUE TITLE
AreaDescriptionManagement example fails at extending ADF

### ISSUE THREAD

**Issue by y22ma** [googlesamples/tango-examples-unity#80] opened 2017-02-13 22:01 UTC
When I select an existing ADF and click extend, the produces the following error message:
```
Failed to connect to Tango Service.
```

Same issue can be reproduced when I set area description learning mode to be true, and start the tango application with an existing ADF in AreaLearning example.

**Comment by chaosemer** [comment] 2017-02-16 22:14
Hi!

Have you customized the samples at all before running it? There are some configuration options that are incompatible. You should see a warning <!> if that is the case.

It'd be really helpful here if you could share a picture of the scene's Tango Application settings as well as a logcat of the run.

**Comment by y22ma** [comment] 2017-02-23 16:11
@chaosemer sorry for the late reply, but no I haven't customized the example. Will follow up with the logcat and screenshot.

**Comment by bradhoekstra** [comment] 2017-02-23 16:34
@chaosemer: I've been working with @y22ma on this and see the same issue. Here are my tango settings and the logcat after I click the start button in the area learning scene.

![screen shot 2017-02-23 at 11 25 49 am](https://cloud.githubusercontent.com/assets/1126869/23268473/e1f9adce-f9bb-11e6-9ce0-c50960b51b8c.png)
[TangoLearningModeLog.txt](https://github.com/googlesamples/tango-examples-unity/files/797080/TangoLearningModeLog.txt)

**Comment by chaosemer** [comment] 2017-02-24 08:47
Thanks for the logcat, I've reported the issue to our internal bug tracker.

**Comment by ryo0ka** [comment] 2017-03-02 10:29
I have been experiencing the same issue.

Seemingly Tango service is set to time out in 10 seconds as it attempts to load an ADF. When the service takes about 10 seconds to load an ADF, it crashes, given any files that are large enough to make it happen.

This issue has been questioned several weeks ago in SO: http://stackoverflow.com/questions/41722328/file-size-limit-for-extending-adfs and as you can see, the above paragraph is the summary of our two's current observation. I hope this helps you identify the cause.

My project deals with a fairly large area - at the moment I would have to learn the whole area whenever a part of it was not learned enough in the previous learning. I would really appreciate that this issue is addressed soon.

**Comment by bradhoekstra** [comment] 2017-03-02 14:36
Yes, this is the same issue. The ADF we were trying to extend was around 120MB.

**Comment by ryo0ka** [comment] 2017-03-02 17:38
Yes this happens with any ADF's that are large enough for the service to take more than about 10 seconds to load. My ADF's whose size is ranged from 110MB to 180MB all crash the service in said exact time. As far as watching debug info, when the service crashes, the memory allocation depends on the size of ADF's.

**Comment by bradhoekstra** [comment] 2017-03-02 17:40
Thanks @ryo0ka. I think ideally, assuming the loading of the ADF cannot be sped up, that the C# API should expose the ability to customize the timeout.

**Comment by ryo0ka** [comment] 2017-03-02 18:29
@bradhoekstra I think so too. However, timeout is not mentioned in API's of either Unity/Java/C, except in the list of exceptions in UX framework as a "critical error" (https://developers.google.com/tango/ux/ux-framework-exceptions). It's probably set internal to the service itself (https://developers.google.com/tango/apis/overview) not providing an access to it not only for Unity's but also C's, which Unity's is based on. I suppose this is not only about Unity API but their decision making as to what of Tango service should be exposed - anyways yes I think this is appreciated to be somehow configurable.

**Comment by rampartisan** [comment] 2017-03-15 16:06
Hey,

I think I am having a similar issue, with saving large meshes at high scanning resolutions. If my issue is the same (not 100%) then I would also like to add my wish for this to be configureable. In the meantime has anyone found a workaround?

**Comment by chaosemer** [comment] 2017-03-15 16:25
Unfortunately, extending existing building-scale area descriptions is not a supported use case. I suggest splitting off the work into two passes: one pass to create an area description for the area you want to reconstruct, and a second pass where you reconstruct the world and load the area description in "Load Existing" mode instead of in "Learning" mode.

Please tell me if this works for you.

**Comment by bradhoekstra** [comment] 2017-03-15 16:32
Unfortunately, this does not work for us. Sometimes we need to add new areas to the ADF after the first scan, and sometimes the initial ADF does not relocalize well in certain areas and needs to be improved. The problem with creating a new ADF is that it invalidates the old co-ordinate frame.

A possibly workaround would be the ability to base a new ADF off the co-ordinate frame of an existing ADF, that doesn't appear to be possible right now either.

**Comment by rampartisan** [comment] 2017-03-15 16:42
Hey chaosemer, the issue i am having is with saving/creating a brand new adf after scanning, if the mesh is too large the adf seems to save (the Device can localise) but the mesh data is empty. It seems that i am timing out when going from tango dynamic mesh to adf mesh and serialising.

**Comment by chaosemer** [comment] 2017-03-15 16:48
@bradhoekstra, unfortunately we do not support the use case of extending area descriptions at building scale. You can localize in another area and then walk to the area you want to mesh.

**Comment by chaosemer** [comment] 2017-03-15 16:50
@rampartisan, I suggest saving the brand new area description without a mesh. Saving an area description disconnects from Tango and takes multiple seconds. Build a mesh in a second pass.

**Comment by rampartisan** [comment] 2017-03-15 20:46
@chaosemer I am unsure what you mean by second pass: a second scan as an extension or create the ADF, reconnect to the tango service and then save the mesh?

**Comment by ryo0ka** [comment] 2017-03-15 23:00
@chaosemer Thank you for your support.

**Comment by chaosemer** [comment] 2017-03-15 23:03
@rampartisan, I would suggest the second of your options. First pass you create an Area Description, then you disconnect from Tango and reconnect without learning mode enabled, just load the Area Description. In this second pass, you create and save the mesh.

**Comment by rampartisan** [comment] 2017-03-16 11:46
@chaosemer I am still a little unclear, this would require a second physical scan by the user?

My current workaround is to call Tango3DRExtractWholeMesh, populate an AreaDescriptionMesh with the data and serialise with a temporary file name BEFORE saving the adf. Then whilst saving the adf I rename this temp file to the ADF uuid.

I currently have an issue loading this mesh, as it can be larger than unity's built in limit but thats a unity issue!

**Comment by chaosemer** [comment] 2017-03-17 02:54
Yes, I'm suggesting a second physical scan, but your idea sounds smoother. 👍 

In general, I do suggest you capture and Area Description in one dedicated pass when possible and avoid opening existing Area Descriptions in learning mode.

I'm going to close this, sounds like you're unblocked.

**Closed as completed by chaosemer** 2017-03-17 02:54 UTC
