### ISSUE TITLE
Tango 3d scanner quality is poor. Could somebody help me how to improve it?

### ISSUE THREAD

**Issue by amitkumbhar14** [googlesamples/tango-examples-unity#70] opened 2017-01-12 06:27 UTC
Hi,

I have tried same demo from the official repo for 3d scanning and i get really poor quality of 3d environment. i have tried change values of tango manager prefab and other settings but still its same.

I have attached screenshot of ExperimentalMeshBuilderWithColor demo.  Please help me what to do ?

![screenshot_20170112-011649](https://cloud.githubusercontent.com/assets/14278250/21879349/41d049c0-d8be-11e6-93b4-ab2157b76827.png)

**Comment by andrewnakas** [comment] 2017-01-12 08:00
Have you tried reducing the resolution of the mesh? This will improve both mesh quality and vertex color texture resolution. You can go as low as 1cm. You can also improve the texture by implementing an image feed to material texture feature to replace the vertex colors system. I would recommend reading Tim Swan's building a holodeck blog posts for some insights.

**Comment by amitkumbhar14** [comment] 2017-01-12 09:18
Hi andrewankas , thax for the help but its still not working. 
what could be the possible changes to be done to improve mesh clarity ?

 
![aa](https://cloud.githubusercontent.com/assets/14278250/21883585/ea764e3c-d8d5-11e6-9f17-6b84c9aea247.jpg)

**Comment by amitkumbhar14** [comment] 2017-01-12 11:52
Thnx Andrew, I tried what you suggested but its not working ... ;( .

**Comment by andrewnakas** [comment] 2017-01-13 19:12
Ok, are you using the Phab or Tablet? Are you trying to improve mesh resolution or texture detail? The tablet has a lower effective resolution. Your image looks on par with the intended results of the 3dr api. 

I saw Lubos' link on your post in the G+ fourms. His github project could be helpful to look at/get some baseline. Its based in c not unity but the concepts are similar. 

 I would check out Tim Swan's blog. He is on a year journey where he is exploring spatial computing by building a holodeck. He has abstracted out chisel and wrote a multifeed scanner that works on kinect and tango built with unity.  It uses material texturing over vertex coloring and is very impressive. Could be some good inspiration/ideas to go forward with this. 
https://github.com/lvonasek/tango

**Comment by miraleung** [comment] 2017-01-26 04:31
This looks like it's working as intended - in Unity, resolution does change with the TangoApplication setting.

**Comment by amitkumbhar14** [comment] 2017-02-01 09:32
Hi @andrewnakas , sorry i was on leave for few days. I'm using lenovo phab2 pro. and im trying to improve both mesh resolution and texture detail as well.

**Comment by chaosemer** [comment] 2017-02-02 21:36
This is working as intended. The colors are only per vertex, which is the best that the reconstruction code can do in realtime. If you want to have better color information, you'll need to do a second optimization pass which the [low level C interface](https://developers.google.com/tango/apis/c/reconstruction/reference/) supports but the Unity interface does not.

I'm going to close this issue since the Unity interface does not currently support your issue.

**Closed as completed by chaosemer** 2017-02-02 21:36 UTC
