### ISSUE TITLE
Tango Application Crashes on rapid motion of the device

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#67] opened 2016-12-20 10:41 UTC
Tango Application Crashes on rapid motion of the device.

**Comment by chaosemer** [comment] 2017-01-05 15:45
Is this with the Tablet dev kit or with a Phab2 Pro?

**Comment by imflash217** [comment] 2017-01-10 11:35
Tab dev Kit

**Comment by chaosemer** [comment] 2017-01-10 20:57
Thanks! This is a duplicate of #52, which we are looking into.

**Closed as completed by chaosemer** 2017-01-10 20:57 UTC
Labels: duplicate
